# Generated by Django 2.1.4 on 2018-12-17 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartNotes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SmartNote',
            new_name='MySmartNote',
        ),
    ]
