# Generated by Django 2.1.4 on 2018-12-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartNotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartnotes',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='smartnotes',
            name='title',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
