# Generated by Django 2.1.4 on 2018-12-17 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smartNotes', '0002_auto_20181213_2025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='smartnotes',
            old_name='notes',
            new_name='context',
        ),
        migrations.RenameField(
            model_name='smartnotes',
            old_name='mentorName',
            new_name='mentor',
        ),
        migrations.RenameField(
            model_name='smartnotes',
            old_name='subjectName',
            new_name='subject',
        ),
    ]
